"""Regenerate SI Unit prefixed-unit data modules.

Computes the prefixed-unit set and the grammar token tables from the
maintained authority tables in paxman/capabilities/SIUnit/rules/data/.
Deterministic: same tables -> identical generated output. Run after editing
any maintained SIUnit data module:

    uv run python tools/regenerate_si_prefix_data.py

--check regenerates in memory and exits non-zero if any generated file
differs (used by tests/capabilities/si_unit/test_data.py). Mirrors
tools/regenerate_isbn_range_data.py.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from paxman.capabilities.SIUnit.rules.data.si_base_units import BASE_UNIT_SYMBOLS
from paxman.capabilities.SIUnit.rules.data.si_derived_units import DERIVED_UNIT_SYMBOLS
from paxman.capabilities.SIUnit.rules.data.si_nonsi_units import NONSI_UNIT_SYMBOLS
from paxman.capabilities.SIUnit.rules.data.si_prefixes import (
    PREFIX_NAMES,
    PREFIX_SYMBOLS,
)
from paxman.capabilities.SIUnit.rules.data.unit_names import NAME_TO_SYMBOL

ROOT = Path(__file__).resolve().parents[1]
RULES_DATA = ROOT / "paxman" / "capabilities" / "SIUnit" / "rules" / "data"
GRAMMAR_DATA = ROOT / "paxman" / "capabilities" / "SIUnit" / "grammar" / "data"

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_si_prefix_data.py — do not edit by hand."
)

# BIPM SI Brochure §3.2 + Table 8 footnote: prefixes are NOT used with
# min/h/d/° ′ ″, °C, or ha; the gram ("g") is the prefix attachment point.
_PREFIXABLE_NONSI = frozenset({"L", "t", "Da", "eV", "u", "Å", "b", "bar"})
_NO_PREFIX = frozenset({"min", "h", "d", "°", "′", "″", "°C", "ha"})


def _prefixable_units() -> frozenset[str]:
    # BIPM §3.2 (D9): prefixes attach to the gram ("g"), not to the
    # kilogram — exclude "kg" so "kkg"/"Mkg"/"µkg" are never generated.
    return (
        (BASE_UNIT_SYMBOLS - {"kg"}) | DERIVED_UNIT_SYMBOLS | _PREFIXABLE_NONSI
    ) - _NO_PREFIX


def _official_symbols() -> frozenset[str]:
    return BASE_UNIT_SYMBOLS | DERIVED_UNIT_SYMBOLS | NONSI_UNIT_SYMBOLS


def _validate_authority_constants() -> None:
    """Fail loudly if the hand-maintained BIPM sets drift from the tables.

    Runs on both the write and --check paths (called from _modules()).
    Raises SystemExit, not assert: this is a data-integrity guard and must
    survive python -O.
    """
    official = _official_symbols()
    if not official >= _PREFIXABLE_NONSI:
        raise SystemExit(
            "_PREFIXABLE_NONSI includes symbols absent from the maintained"
            f" authority tables: {sorted(_PREFIXABLE_NONSI - official)}"
        )
    if not official >= _NO_PREFIX:
        raise SystemExit(
            "_NO_PREFIX includes symbols absent from the maintained"
            f" authority tables: {sorted(_NO_PREFIX - official)}"
        )
    if not _PREFIXABLE_NONSI.isdisjoint(_NO_PREFIX):
        raise SystemExit(
            "_PREFIXABLE_NONSI and _NO_PREFIX overlap:"
            f" {sorted(_PREFIXABLE_NONSI & _NO_PREFIX)}"
        )


def _prefixed_symbols() -> frozenset[str]:
    """Prefix + prefixable unit, excluding official-symbol collisions."""
    official = _official_symbols()
    return frozenset(
        prefix + unit
        for prefix in PREFIX_SYMBOLS
        for unit in _prefixable_units()
        if prefix + unit not in official
    )


def _longest_first(tokens: set[str] | frozenset[str]) -> tuple[str, ...]:
    return tuple(sorted(tokens, key=lambda t: (-len(t), t)))


def _symbol_tokens() -> tuple[str, ...]:
    return _longest_first(_official_symbols() | PREFIX_SYMBOLS | _prefixed_symbols())


def _prefixed_name_to_symbol() -> dict[str, str]:
    """Prefixed name -> prefixed symbol, excluding official-name collisions.

    BIPM §3.2 (D9): prefix name + unit name ("mega" + "hertz") maps to the
    prefixed symbol ("MHz"). "kilogram" is never regenerated as kilo+gram —
    official names win (D8).
    """
    official = frozenset(NAME_TO_SYMBOL)
    # Last-write-wins by dict order: if two names share a symbol (e.g.
    # "litre"/"liter" -> "L"), the maintained table's later entry wins.
    # Both spellings resolve to the same symbol, so the collision is
    # harmless for symbol generation — keep the maintained order stable.
    symbol_to_name = {v: k for k, v in NAME_TO_SYMBOL.items()}
    result: dict[str, str] = {}
    for prefix_symbol, prefix_name in PREFIX_NAMES.items():
        for unit_symbol in _prefixable_units():
            unit_name = symbol_to_name.get(unit_symbol)
            if unit_name is None:
                continue
            name = prefix_name + unit_name
            symbol = prefix_symbol + unit_symbol
            if name not in official and symbol in _prefixed_symbols():
                if name in result:
                    raise SystemExit(
                        "generated prefixed name collision:"
                        f" {name!r} from {prefix_name!r}+{unit_name!r}"
                    )
                result[name] = symbol
    return result


def _name_tokens() -> tuple[str, ...]:
    return _longest_first(
        frozenset(NAME_TO_SYMBOL) | frozenset(_prefixed_name_to_symbol())
    )


def _emit_module(docstring: str, assignment: str) -> str:
    """Assemble a generated module: header docstring, future import, assignment."""
    return (
        '"""' + _GENERATED_HEADER + "\n\n" + docstring + '"""\n\n'
        "from __future__ import annotations\n\n" + assignment + "\n"
    )


def _emit_prefixed_units() -> str:
    symbols = sorted(_prefixed_symbols())
    items = "".join(f'        "{symbol}",\n' for symbol in symbols)
    assignment = (
        "PREFIXED_UNIT_SYMBOLS: frozenset[str] = frozenset(\n"
        "    {\n" + items + "    }\n"
        ")"
    )
    docstring = (
        "Prefixed SI unit symbols: every BIPM SI Brochure (9th ed., 2019)\n"
        "Table 5 prefix applied to every prefixable unit, excluding\n"
        'official-symbol collisions (e.g. "kg"; "cd" never arises because\n'
        'the day "d" is not prefixable). Derived from the maintained\n'
        "authority tables — regenerate via the tool after edits.\n"
    )
    return _emit_module(docstring, assignment)


def _emit_prefixed_unit_names() -> str:
    entries = "".join(
        f'    "{name}": "{symbol}",\n'
        for name, symbol in sorted(_prefixed_name_to_symbol().items())
    )
    assignment = "PREFIXED_NAME_TO_SYMBOL: dict[str, str] = {\n" + entries + "}"
    docstring = (
        "Prefixed unit names -> prefixed symbols (BIPM SI Brochure, 9th ed.,\n"
        '2019): "mega" + "hertz" -> "MHz". Official names win over\n'
        'regenerated collisions ("kilogram" is never kilo+gram). Sorted by\n'
        "name for deterministic output. Derived from the maintained authority\n"
        "tables — regenerate via the tool after edits.\n"
    )
    return _emit_module(docstring, assignment)


def _emit_symbol_tokens() -> str:
    tokens = _symbol_tokens()
    items = "".join(f'    "{token}",\n' for token in tokens)
    assignment = "SYMBOL_TOKENS: tuple[str, ...] = (\n" + items + ")"
    docstring = (
        "Every recognized unit-symbol token, longest-first: the official\n"
        "symbols, the SI prefixes, and the prefixed symbols. Longest-first\n"
        "ordering lets a scanner prefer the longest match. Derived from the\n"
        "maintained authority tables — regenerate via the tool after edits.\n"
    )
    return _emit_module(docstring, assignment)


def _emit_name_tokens() -> str:
    tokens = _name_tokens()
    items = "".join(f'    "{token}",\n' for token in tokens)
    assignment = "NAME_TOKENS: tuple[str, ...] = (\n" + items + ")"
    docstring = (
        "Every recognized unit-name token, longest-first: the maintained\n"
        'names plus the prefixed names ("mega" + "hertz" -> "megahertz").\n'
        "Longest-first ordering lets a scanner prefer the longest match.\n"
        "Derived from the maintained authority tables — regenerate via the\n"
        "tool after edits.\n"
    )
    return _emit_module(docstring, assignment)


def _emit_compound_tokens() -> str:
    assignment = (
        'COMPOUND_SEPARATORS: str = "/·⋅"\n'
        'EXPONENT_CHARACTERS: str = r"0-9⁻⁰¹²³⁴⁵⁶⁷⁸⁹\\-"'
    )
    docstring = (
        "Compound-unit token characters (BIPM SI Brochure, 9th ed., §5.4\n"
        "and §5.3.4): COMPOUND_SEPARATORS are the multiplication signs\n"
        "accepted between unit factors (slash, middle dot U+00B7, dot\n"
        "operator U+22C5); EXPONENT_CHARACTERS is a regex character-class\n"
        "fragment for integer powers — ASCII digits, superscript digits\n"
        "(U+2070, U+00B9-U+00B3, U+2074-U+2079), superscript minus (U+207B),\n"
        "and the hyphen-minus. The Task 6 compound rule keeps its own split\n"
        "patterns locally — it never imports from grammar/.\n"
    )
    return _emit_module(docstring, assignment)


def _modules() -> list[tuple[Path, str]]:
    """The five generated modules, in deterministic write order."""
    _validate_authority_constants()
    return [
        (RULES_DATA / "prefixed_units.py", _emit_prefixed_units()),
        (RULES_DATA / "prefixed_unit_names.py", _emit_prefixed_unit_names()),
        (GRAMMAR_DATA / "unit_symbol_tokens.py", _emit_symbol_tokens()),
        (GRAMMAR_DATA / "unit_name_tokens.py", _emit_name_tokens()),
        (GRAMMAR_DATA / "compound_tokens.py", _emit_compound_tokens()),
    ]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate the SI Unit prefixed-unit data modules."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if any module drifts",
    )
    args = parser.parse_args()

    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("all generated SIUnit data modules are up to date")
        return

    for path, text in modules:
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
