"""GENERATED by tools/regenerate_si_prefix_data.py — do not edit by hand.

Compound-unit token characters (BIPM SI Brochure, 9th ed., §5.4
and §5.3.4): COMPOUND_SEPARATORS are the multiplication signs
accepted between unit factors (slash, middle dot U+00B7, dot
operator U+22C5); EXPONENT_CHARACTERS is a regex character-class
fragment for integer powers — ASCII digits, superscript digits
(U+2070, U+00B9-U+00B3, U+2074-U+2079), superscript minus (U+207B),
and the hyphen-minus. The Task 6 compound rule keeps its own split
patterns locally — it never imports from grammar/.
"""

from __future__ import annotations

COMPOUND_SEPARATORS: str = "/·⋅"
EXPONENT_CHARACTERS: str = r"0-9⁻⁰¹²³⁴⁵⁶⁷⁸⁹\-"
