"""ISO 3166-1 lookup tables for Country capability.

All tables are derived from ISO 3166-1:2024.
Source: https://www.iso.org/standard/396855.html
"""

from __future__ import annotations

# Alpha-2 codes (249 assigned)
ALPHA2_CODES: frozenset[str] = frozenset({
    "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR",
    "AS", "AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE",
    "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ",
    "BR", "BS", "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD",
    "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR",
    "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM",
    "DO", "DZ", "EC", "EE", "EG", "EH", "ER", "ES", "ET", "FI",
    "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF",
    "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS",
    "GT", "GU", "GW", "GY", "HK", "HM", "HN", "HR", "HT", "HU",
    "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT",
    "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN",
    "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK",
    "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME",
    "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ",
    "MR", "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA",
    "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU",
    "NZ", "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM",
    "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS",
    "RU", "RW", "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI",
    "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV",
    "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK",
    "TL", "TM", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA",
    "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI",
    "VN", "VU", "WF", "WS", "XK", "YE", "YT", "ZA", "ZM", "ZW",
})

# Alpha-3 to Alpha-2 mapping (249 entries)
ALPHA3_TO_ALPHA2: dict[str, str] = {
    "ABW": "AW", "AFG": "AF", "AGO": "AO", "AIA": "AI", "ALA": "AX",
    "ALB": "AL", "AND": "AD", "ARE": "AE", "ARG": "AR", "ARM": "AM",
    "ASM": "AS", "ATA": "AQ", "ATF": "TF", "ATG": "AG", "AUS": "AU",
    "AUT": "AT", "AZE": "AZ", "BDI": "BI", "BEL": "BE", "BEN": "BJ",
    "BES": "BQ", "BFA": "BF", "BGD": "BD", "BGR": "BG", "BHR": "BH",
    "BHS": "BS", "BIH": "BA", "BLM": "BL", "BLR": "BY", "BLZ": "BZ",
    "BMU": "BM", "BOL": "BO", "BRA": "BR", "BRB": "BB", "BRN": "BN",
    "BTN": "BT", "BVT": "BV", "BWA": "BW", "CAF": "CF", "CAN": "CA",
    "CCK": "CC", "CHE": "CH", "CHL": "CL", "CHN": "CN", "CIV": "CI",
    "CMR": "CM", "COD": "CD", "COG": "CG", "COK": "CK", "COL": "CO",
    "COM": "KM", "CPV": "CV", "CRI": "CR", "CUB": "CU", "CUW": "CW",
    "CXR": "CX", "CYM": "KY", "CYP": "CY", "CZE": "CZ", "DEU": "DE",
    "DJI": "DJ", "DMA": "DM", "DNK": "DK", "DOM": "DO", "DZA": "DZ",
    "ECU": "EC", "EGY": "EG", "ERI": "ER", "ESH": "EH", "ESP": "ES",
    "EST": "EE", "ETH": "ET", "FIN": "FI", "FJI": "FJ", "FLK": "FK",
    "FRA": "FR", "FRO": "FO", "FSM": "FM", "GAB": "GA", "GBR": "GB",
    "GEO": "GE", "GGY": "GG", "GHA": "GH", "GIB": "GI", "GIN": "GN",
    "GLP": "GP", "GMB": "GM", "GNB": "GW", "GNQ": "GQ", "GRC": "GR",
    "GRD": "GD", "GRL": "GL", "GTM": "GT", "GUF": "GF", "GUM": "GU",
    "GUY": "GY", "HKG": "HK", "HMD": "HM", "HND": "HN", "HRV": "HR",
    "HTI": "HT", "HUN": "HU", "IDN": "ID", "IMN": "IM", "IND": "IN",
    "IOT": "IO", "IRL": "IE", "IRN": "IR", "IRQ": "IQ", "ISL": "IS",
    "ISR": "IL", "ITA": "IT", "JAM": "JM", "JEY": "JE", "JOR": "JO",
    "JPN": "JP", "KAZ": "KZ", "KEN": "KE", "KGZ": "KG", "KHM": "KH",
    "KIR": "KI", "KNA": "KN", "KOR": "KR", "KWT": "KW", "LAO": "LA",
    "LBN": "LB", "LBR": "LR", "LBY": "LY", "LCA": "LC", "LIE": "LI",
    "LKA": "LK", "LSO": "LS", "LTU": "LT", "LUX": "LU", "LVA": "LV",
    "MAR": "MA", "MCO": "MC", "MDA": "MD", "MDG": "MG", "MDV": "MV",
    "MEX": "MX", "MHL": "MH", "MKD": "MK", "MLI": "ML", "MLT": "MT",
    "MMR": "MM", "MNE": "ME", "MNG": "MN", "MNP": "MP", "MOZ": "MZ",
    "MRT": "MR", "MSR": "MS", "MTQ": "MQ", "MUS": "MU", "MWI": "MW",
    "MYS": "MY", "MYT": "YT", "NAM": "NA", "NCL": "NC", "NER": "NE",
    "NFK": "NF", "NGA": "NG", "NIC": "NI", "NIU": "NU", "NLD": "NL",
    "NOR": "NO", "NPL": "NP", "NRU": "NR", "NZL": "NZ", "OMN": "OM",
    "PAK": "PK", "PAN": "PA", "PCN": "PN", "PER": "PE", "PHL": "PH",
    "PLW": "PW", "PNG": "PG", "POL": "PL", "PRI": "PR", "PRK": "KP",
    "PRT": "PT", "PRY": "PY", "PSE": "PS", "PYF": "PF", "QAT": "QA",
    "REU": "RE", "ROU": "RO", "RUS": "RU", "RWA": "RW", "SAU": "SA",
    "SDN": "SD", "SEN": "SN", "SGP": "SG", "SGS": "GS", "SHN": "SH",
    "SJM": "SJ", "SLB": "SB", "SLE": "SL", "SLV": "SV", "SMR": "SM",
    "SOM": "SO", "SPM": "PM", "SRB": "RS", "SSD": "SS", "STP": "ST",
    "SUR": "SR", "SVK": "SK", "SVN": "SI", "SWE": "SE", "SWZ": "SZ",
    "SXM": "SX", "SYC": "SC", "SYR": "SY", "TCA": "TC", "TCD": "TD",
    "TGO": "TG", "THA": "TH", "TJK": "TJ", "TKL": "TK", "TKM": "TM",
    "TLS": "TL", "TON": "TO", "TTO": "TT", "TUN": "TN", "TUR": "TR",
    "TUV": "TV", "TWN": "TW", "TZA": "TZ", "UGA": "UG", "UKR": "UA",
    "UMI": "UM", "URY": "UY", "USA": "US", "UZB": "UZ", "VAT": "VA",
    "VCT": "VC", "VEN": "VE", "VGB": "VG", "VIR": "VI", "VNM": "VN",
    "VUT": "VU", "WLF": "WF", "WSM": "WS", "XKX": "XK", "YEM": "YE",
    "ZAF": "ZA", "ZMB": "ZM", "ZWE": "ZW",
}

# Numeric (M49) to Alpha-2 mapping (249 entries)
NUMERIC_TO_ALPHA2: dict[str, str] = {
    "004": "AF", "008": "AL", "010": "AQ", "012": "DZ", "016": "AS",
    "020": "AD", "024": "AO", "028": "AG", "031": "AZ", "032": "AR",
    "036": "AU", "040": "AT", "044": "BS", "048": "BH", "050": "BD",
    "051": "AM", "052": "BB", "056": "BE", "060": "BM", "064": "BT",
    "068": "BO", "070": "BA", "072": "BW", "074": "BV", "076": "BR",
    "084": "BZ", "086": "IO", "090": "SB", "092": "VG", "096": "BN",
    "100": "BG", "104": "MM", "108": "BI", "112": "BY", "116": "KH",
    "120": "CM", "124": "CA", "132": "CV", "136": "KY", "140": "CF",
    "144": "LK", "148": "TD", "152": "CL", "156": "CN", "158": "TW",
    "162": "CX", "166": "CC", "170": "CO", "174": "KM", "175": "YT",
    "178": "CG", "180": "CD", "184": "CK", "188": "CR", "191": "HR",
    "192": "CU", "196": "CY", "200": "CS", "203": "CZ", "204": "BJ",
    "208": "DK", "212": "DM", "214": "DO", "218": "EC", "222": "SV",
    "226": "GQ", "231": "ET", "232": "ER", "233": "EE", "234": "FO",
    "238": "FK", "242": "FJ", "246": "FI", "250": "FR", "254": "GF",
    "258": "PF", "260": "TF", "262": "DJ", "266": "GA", "268": "GE",
    "270": "GM", "275": "PS", "276": "DE", "288": "GH", "292": "GI",
    "296": "KI", "300": "GR", "304": "GL", "308": "GD", "312": "GP",
    "316": "GU", "320": "GT", "324": "GN", "328": "GY", "332": "HT",
    "336": "VA", "340": "HN", "344": "HK", "348": "HU", "352": "IS",
    "356": "IN", "360": "ID", "364": "IR", "368": "IQ", "372": "IE",
    "376": "IL", "380": "IT", "384": "CI", "388": "JM", "392": "JP",
    "398": "KZ", "400": "JO", "404": "KE", "408": "KP", "410": "KR",
    "414": "KW", "417": "KG", "418": "LA", "422": "LB", "426": "LS",
    "428": "LV", "430": "LR", "434": "LY", "438": "LI", "440": "LT",
    "442": "LU", "446": "MO", "450": "MG", "454": "MW", "458": "MY",
    "462": "MV", "466": "ML", "470": "MT", "474": "MQ", "478": "MR",
    "480": "MU", "484": "MX", "492": "MC", "496": "MN", "498": "MD",
    "499": "ME", "500": "MS", "504": "MA", "508": "MZ", "512": "OM",
    "516": "NA", "520": "NR", "524": "NP", "528": "NL", "530": "AN",
    "540": "NC", "548": "VU", "554": "NZ", "558": "NI", "562": "NE",
    "566": "NG", "570": "NU", "574": "NF", "578": "NO", "580": "MP",
    "583": "FM", "584": "MH", "585": "PW", "586": "PK", "591": "PA",
    "598": "PG", "600": "PY", "604": "PE", "608": "PH", "612": "PN",
    "616": "PL", "620": "PT", "624": "GW", "626": "TL", "630": "PR",
    "634": "QA", "638": "RE", "642": "RO", "643": "RU", "646": "RW",
    "654": "SH", "659": "KN", "660": "AI", "662": "LC", "666": "PM",
    "670": "VC", "674": "SM", "678": "ST", "682": "SA", "686": "SN",
    "688": "RS", "690": "SC", "694": "SL", "702": "SG", "703": "SK",
    "704": "VN", "705": "SI", "706": "SO", "710": "ZA", "716": "ZW",
    "724": "ES", "728": "SS", "732": "EH", "736": "SD", "740": "SR",
    "744": "SJ", "748": "SZ", "752": "SE", "756": "CH", "760": "SY",
    "762": "TJ", "764": "TH", "768": "TG", "772": "TK", "776": "TO",
    "780": "TT", "784": "AE", "788": "TN", "792": "TR", "795": "TM",
    "796": "TC", "798": "TV", "800": "UG", "804": "UA", "807": "MK",
    "818": "EG", "826": "GB", "831": "GG", "832": "JE", "833": "IM",
    "834": "TZ", "840": "US", "850": "VI", "854": "BF", "858": "UY",
    "860": "UZ", "862": "VE", "876": "WF", "882": "WS", "887": "YE",
    "894": "ZM", "-99": "XK",
}

# Official English short names (249 entries, uppercased)
NAME_TO_ALPHA2: dict[str, str] = {
    "AFGHANISTAN": "AF", "ALBANIA": "AL", "ALGERIA": "DZ",
    "AMERICAN SAMOA": "AS", "ANDORRA": "AD", "ANGOLA": "AO",
    "ANTIGUA AND BARBUDA": "AG", "ARGENTINA": "AR", "ARMENIA": "AM",
    "ARUBA": "AW", "AUSTRALIA": "AU", "AUSTRIA": "AT",
    "AZERBAIJAN": "AZ", "BAHAMAS": "BS", "BAHRAIN": "BH",
    "BANGLADESH": "BD", "BARBADOS": "BB", "BELARUS": "BY",
    "BELGIUM": "BE", "BELIZE": "BZ", "BENIN": "BJ",
    "BERMUDA": "BM", "BHUTAN": "BT", "BOLIVIA": "BO",
    "BOSNIA AND HERZEGOVINA": "BA", "BOTSWANA": "BW", "BRAZIL": "BR",
    "BRITISH VIRGIN ISLANDS": "VG", "BRUNEI": "BN", "BULGARIA": "BG",
    "BURKINA FASO": "BF", "BURUNDI": "BI", "CAMBODIA": "KH",
    "CAMEROON": "CM", "CANADA": "CA", "CAPE VERDE": "CV",
    "CAYMAN ISLANDS": "KY", "CENTRAL AFRICAN REPUBLIC": "CF",
    "CHAD": "TD", "CHILE": "CL", "CHINA": "CN",
    "COLOMBIA": "CO", "COMOROS": "KM", "CONGO": "CG",
    "COOK ISLANDS": "CK", "COSTA RICA": "CR", "CROATIA": "HR",
    "CUBA": "CU", "CURACAO": "CW", "CYPRUS": "CY",
    "CZECHIA": "CZ", "DEMOCRATIC REPUBLIC OF THE CONGO": "CD",
    "DENMARK": "DK", "DJIBOUTI": "DJ", "DOMINICA": "DM",
    "DOMINICAN REPUBLIC": "DO", "ECUADOR": "EC", "EGYPT": "EG",
    "EL SALVADOR": "SV", "EQUATORIAL GUINEA": "GQ", "ERITREA": "ER",
    "ESTONIA": "EE", "ESWATINI": "SZ", "ETHIOPIA": "ET",
    "FALKLAND ISLANDS": "FK", "FIJI": "FJ", "FINLAND": "FI",
    "FRANCE": "FR", "FRENCH GUIANA": "GF", "FRENCH POLYNESIA": "PF",
    "GABON": "GA", "GAMBIA": "GM", "GEORGIA": "GE",
    "GERMANY": "DE", "GHANA": "GH", "GIBRALTAR": "GI",
    "GREECE": "GR", "GREENLAND": "GL", "GRENADA": "GD",
    "GUADELOUPE": "GP", "GUAM": "GU", "GUATEMALA": "GT",
    "GUERNSEY": "GG", "GUINEA": "GN", "GUINEA-BISSAU": "GW",
    "GUYANA": "GY", "HAITI": "HT", "HONDURAS": "HN",
    "HONG KONG": "HK", "HUNGARY": "HU", "ICELAND": "IS",
    "INDIA": "IN", "INDONESIA": "ID", "IRAN": "IR",
    "IRAQ": "IQ", "IRELAND": "IE", "ISLE OF MAN": "IM",
    "ISRAEL": "IL", "ITALY": "IT", "IVORY COAST": "CI",
    "JAMAICA": "JM", "JAPAN": "JP", "JERSEY": "JE",
    "JORDAN": "JO", "KAZAKHSTAN": "KZ", "KENYA": "KE",
    "KIRIBATI": "KI", "KOSOVO": "XK", "KUWAIT": "KW",
    "KYRGYZSTAN": "KG", "LAOS": "LA", "LATVIA": "LV",
    "LEBANON": "LB", "LESOTHO": "LS", "LIBERIA": "LR",
    "LIBYA": "LY", "LIECHTENSTEIN": "LI", "LITHUANIA": "LT",
    "LUXEMBOURG": "LU", "MACAU": "MO", "MADAGASCAR": "MG",
    "MALAWI": "MW", "MALAYSIA": "MY", "MALDIVES": "MV",
    "MALI": "ML", "MALTA": "MT", "MARSHALL ISLANDS": "MH",
    "MARTINIQUE": "MQ", "MAURITANIA": "MR", "MAURITIUS": "MU",
    "MAYOTTE": "YT", "MEXICO": "MX", "MICRONESIA": "FM",
    "MOLDOVA": "MD", "MONACO": "MC", "MONGOLIA": "MN",
    "MONTENEGRO": "ME", "MONTSERRAT": "MS", "MOROCCO": "MA",
    "MOZAMBIQUE": "MZ", "MYANMAR": "MM", "NAMIBIA": "NA",
    "NAURU": "NR", "NEPAL": "NP", "NETHERLANDS": "NL",
    "NEW CALEDONIA": "NC", "NEW ZEALAND": "NZ", "NICARAGUA": "NI",
    "NIGER": "NE", "NIGERIA": "NG", "NIUE": "NU",
    "NORFOLK ISLAND": "NF", "NORTH KOREA": "KP", "NORTH MACEDONIA": "MK",
    "NORTHERN MARIANA ISLANDS": "MP", "NORWAY": "NO", "OMAN": "OM",
    "PAKISTAN": "PK", "PALAU": "PW", "PALESTINE": "PS",
    "PANAMA": "PA", "PAPUA NEW GUINEA": "PG", "PARAGUAY": "PY",
    "PERU": "PE", "PHILIPPINES": "PH", "PITCAIRN ISLANDS": "PN",
    "POLAND": "PL", "PORTUGAL": "PT", "PUERTO RICO": "PR",
    "QATAR": "QA", "REUNION": "RE", "ROMANIA": "RO",
    "RUSSIA": "RU", "RWANDA": "RW", "SAINT BARTHELEMY": "BL",
    "SAINT HELENA": "SH", "SAINT KITTS AND NEVIS": "KN",
    "SAINT LUCIA": "LC", "SAINT MARTIN": "MF",
    "SAINT PIERRE AND MIQUELON": "PM", "SAINT VINCENT AND THE GRENADINES": "VC",
    "SAMOA": "WS", "SAN MARINO": "SM", "SAO TOME AND PRINCIPE": "ST",
    "SAUDI ARABIA": "SA", "SENEGAL": "SN", "SERBIA": "RS",
    "SEYCHELLES": "SC", "SIERRA LEONE": "SL", "SINGAPORE": "SG",
    "SLOVAKIA": "SK", "SLOVENIA": "SI", "SOLOMON ISLANDS": "SB",
    "SOMALIA": "SO", "SOUTH AFRICA": "ZA", "SOUTH KOREA": "KR",
    "SOUTH SUDAN": "SS", "SPAIN": "ES", "SRI LANKA": "LK",
    "SUDAN": "SD", "SURINAME": "SR", "SWEDEN": "SE",
    "SWITZERLAND": "CH", "SYRIA": "SY", "TAIWAN": "TW",
    "TAJIKISTAN": "TJ", "TANZANIA": "TZ", "THAILAND": "TH",
    "TIMOR-LESTE": "TL", "TOGO": "TG", "TOKELAU": "TK",
    "TONGA": "TO", "TRINIDAD AND TOBAGO": "TT", "TUNISIA": "TN",
    "TURKEY": "TR", "TURKMENISTAN": "TM", "TURKS AND CAICOS ISLANDS": "TC",
    "TUVALU": "TV", "UGANDA": "UG", "UKRAINE": "UA",
    "UNITED ARAB EMIRATES": "AE", "UNITED KINGDOM": "GB",
    "UNITED STATES": "US", "UNITED STATES VIRGIN ISLANDS": "VI",
    "URUGUAY": "UY", "UZBEKISTAN": "UZ", "VANUATU": "VU",
    "VATICAN CITY": "VA", "VENEZUELA": "VE", "VIETNAM": "VN",
    "WALLIS AND FUTUNA": "WF", "WESTERN SAHARA": "EH", "YEMEN": "YE",
    "ZAMBIA": "ZM", "ZIMBABWE": "ZW",
}

# Common aliases (uppercased)
SYNONYM_TO_ALPHA2: dict[str, str] = {
    "USA": "US", "UK": "GB", "UAE": "AE", "PRC": "CN",
    "DRC": "CD", "DPRK": "KP", "ROK": "KR", "USSR": "RU",
    "UAR": "EG", "CDI": "CI", "RSA": "ZA", "TLS": "TL",
    "CAR": "CF", "PNG": "PG", "SWZ": "SZ", "SKN": "KN",
    "LCA": "LC", "VCT": "VC", "TCT": "TC", "BVI": "VG",
    "USVI": "VI", "CAY": "KY", "FR GUIANA": "GF", "FRENCH GUIANA": "GF",
    "HKG": "HK", "MOZ": "MZ", "COD": "CD", "COG": "CG",
    "DOM": "DO", "EL SAL": "SV", "EQUatorial GUINEA": "GQ",
    "HOND": "HN", "NICAR": "NI", "PAN": "PA", "PARAG": "PY",
    "TRINIDAD": "TT", "UZBEK": "UZ", "VENEZ": "VE",
}
